### ISSUE TITLE
Non XML file causing parser error

### ISSUE THREAD

**Issue by johnadamsDFID** [pwyf/iatikit#48]
Parsing the full IATI dataset today I get the following error

`  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError

  File "__iatikitcache__/registry/data/rikolto/rikolto-international2017org.xml", line 1
XMLSyntaxError: Document is empty, line 1, column 1`

This is because the file location is returning an HTML page for this new publisher's data (https://iatiregistry.org/publisher/rikolto). 

Is there a way of handling this better (try..catch model)?

**Comment by andylolz** [comment]
Hi @johnadamsDFID,

Thanks for this!

I ran into exactly the same thing, and _thought_ I fixed it at version 2.2.2. Are you able to check which version you are running? You should be able to run the following:

```python
import iatikit

print(iatikit.__version__)
```

If it’s earlier than v2.2.2, could you try running a `pip install --upgrade`, [as shown in the installation](https://iatikit.readthedocs.io/en/stable/getting-started.html#installation)?

If the problem persists when using v2.2.2 or later, would you mind providing steps to reproduce? I.e. just a few commands I can run locally to hit the same error. Apologies in advance if the steps are obvious!

Thanks again,

**Comment by johnadamsDFID** [comment]
@andylolz Thanks, using 2.2.4 solved the problem. Thanks for the upgrade instructions. I didn't realise Jupyter didn't reload from the source each time.

**Comment by andylolz** [comment]
Excellent! Thanks @johnadamsDFID.
